spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: react-spring
      spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 534325369877-7kr3hd5br482k4g89lcsfs9r0a4hvkvp.apps.googleusercontent.com
            client-secret: hcIVWLfpYQsbNBtsXUszdQZz
            scope:
              - email
              - profile
logging:
  level:
    org.springframework.security: DEBUG